#!/bin/bash

source ./ovn_functions.sh

while [ 1 ]
do
	GET_MANAGED_SITE_LIST
	for SITE in $MANAGED_SITES
	do
		SITE_CTL_IP=`GET_SITE_CTL_IP $SITE`
		GET_BRIDGE_LIST $SITE_CTL_IP $SITE
		MANAGE_SITE_CONNECTIVITY $SITE_CTL_IP $SITE
		MANAGE_SITE_BRIDGE $SITE_CTL_IP
	done
	MANAGE_TUNNEL_STATUS
done
